server:
  port: 9090  # The Gateway Microservice will run on port 8080
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders:
              - "*"
      routes:

        # Route to Authentication Microservice
        - id: authentication-route
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        # Route to Test Generator Microservice
        - id: test-generator-route
          uri: http://localhost:8082 # Correction ici
          predicates:
            - Path=/test/generate_code

        # Route to Report Generator Microservice
        - id: report-generator-route
          uri: http://localhost:8081  # Correction ici
          predicates:
            - Path=/reports/**

        # Route to Test Analysis Microservice
        - id: test-analysis-route
          uri: http://localhost:8083
          predicates:
            - Path=/analyse/code

      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka  # URL du serveur Eureka
          register-with-eureka: true  # Permet le registre auprès d'Eureka
          fetch-registry: true