server:
  port: 9090  # The Gateway Microservice will run on port 8080

spring:
  application:
    name: gateway-microservice  # Name of the Gateway Microservice
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders:
              - "*"
      routes:
        # Route to Authentication Microservice
        - id: authentication-route
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**

        # Route to Test Generator Microservice
        - id: test-generator-route
          uri: http://localhost:8082
          predicates:
            - Path=/test/generate_code

        # Route to Report Generator Microservice
        - id: report-generator-route
          uri: http://localhost:8081
          predicates:
            - Path=/reports/**

        # Route to Test Analysis Microservice
        - id: test-analysis-route
          uri: http://localhost:8083
          predicates:
            - Path=/analyse/code

    discovery:
      locator:
        enabled: true  # Enables dynamic discovery of microservices registered in Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL for Eureka Server
    fetch-registry: true  # Fetch the registry to discover microservices
    register-with-eureka: true  # Register the Gateway with Eureka for discovery
